---
title: "GPS_survey_DA"
author: "Jonathan Slaney"
date: "12/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Packages
```{r}
library(lmtest)
library(tidyverse)
library(ggplot2)
library(haven)
library(janitor)
library(pastecs)
library(psych)
library(car)
library(Hmisc)
library(ggm)
library(polycor)
library(tableone)
library(forcats)
library(gmodels)
library(QuantPsyc)
library(KernSmooth)
library(raster)
library(sp)
library(sf)
```

## Subset to get only W2 from vic_complete

```{r}
## Load in W1 + w2 merged data
#victoria_small_merged_1 <- read_csv("victoria_small_merged_1.csv")
## Subset for w2 only

## Before I do this, add a column in SD_vic_all to identify sensedoc (1) 
sd2 <- subset(vic_complete, sensedoc.y == 2)

```

## Health Status
```{r}

## Comparson method
tabyl(vic_complete$sf1)

vic_complete <- vic_complete %>% mutate(health_status = case_when(
  sf1 == 1 ~ "Excellent",
  sf1 == 2 ~ "Very Good", 
  sf1 == 3 ~ "Good",
  sf1 == 4 ~ "Fair", 
  sf1 == 5 ~ "Poor"
))

vic_complete$health_status <- factor(vic_complete$health_status, c("Poor", "Fair", "Good", "Very Good", "Excellent"))
tabyl(vic_complete$health_status)

# Table

t_healthy <- vic_complete %>%
          group_by(wave_id, vic_complete$health_status) %>%
            summarise(n = n()) %>%
            mutate(pct = 100*n / sum(n))

kable(t_healthy)
```

## Marital Status
```{r}
tabyl(vic_complete$marital)

# Table

t_wed <- vic_complete %>%
          group_by(wave_id, vic_complete$marital) %>%
            summarise(n = n()) %>%
            mutate(pct = 100*n / sum(n))

kable(t_wed)


tabyl(victoria_small_merged_1$marital)
marital_plot <- ggplot(data = victoria_small_merged_1, aes(marital)) +
  geom_bar() +
  labs(title = "Marital Status",
       x = "Marital Status",
       y = "Number of Participants (n)") + theme(axis.text.x = element_text(angle=60, hjust=1))
plot(marital_plot)
```

## Ethnicity 
```{r}
tabyl(vic_complete$ethnicity)

# Table

t_eth <- vic_complete %>%
          group_by(wave_id, vic_complete$ethnicity) %>%
            summarise(n = n()) %>%
            mutate(pct = 100*n / sum(n))
kable(t_eth)
```

## Income
```{r}
tabyl(vic_complete$income.x)

vic_complete <- vic_complete %>% mutate(income_2 = case_when(
  income == 1 ~ "$49,000 or less",
  income == 2 ~ "$49,000 or less", 
  income == 3 ~ "$49,000 or less",
  income == 4 ~ "$49,000 or less", 
  income == 5 ~ "$49,000 or less",
  income == 6 ~ "$49,000 or less",
  income == 7 ~ "$49,000 or less",
  income == 8 ~ "$50,000 to $99,999",
  income == 9 ~ "$100,000 to $149,999",
  income == 10 ~ "$150,000 or more",
  income == 11 ~ "$150,000 or more",
  income == 77 ~ "I don't know/Prefer not to answer"
)) 

vic_complete$income_1 <- factor(vic_complete$income_1, c("No income", "$1 to $9,999", "$10,000 to $14,999", "$15,000 to $19,999", "$20,000 to $29,999", "$30,000 to $39,999", "$40,000 to $49,999","$50,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999", "$200,000 or more", "I don't know/Prefer not to answer"))

tabyl(vic_complete$income_2)
summary(vic_complete$income)

# Table

t_income_sd <- vic_complete %>%
          group_by(wave_id, vic_complete$income_2) %>%
            summarise(n = n()) %>%
            mutate(pct = 100*n / sum(n))

kable(t_income_sd)
```

## Children 
```{r}
vic_complete <- vic_complete %>% mutate(children_1 = case_when(
  children == 1 ~ "Yes",
  children == 2 ~ "No"
))
tabyl(vic_complete$children_1)
# Table

t_kids <- vic_complete %>%
          group_by(wave_id, vic_complete$children_1) %>%
            summarise(n = n()) %>%
            mutate(pct = n / sum(n))

kable(t_kids)
```

## Born in Canada
```{r}
tabyl(vic_complete$born_can)

vic_mf <- vic_complete %>% mutate(born_canada = case_when(
  born_can == 1 ~ "Yes",
  born_can == 2 ~ "No"
))
tabyl(vic_complete$born_canada)

# Table

t_cana  <- vic_complete %>%
          group_by(wave_id, vic_complete$born_canada) %>%
            summarise(n = n()) %>%
            mutate(pct = n / sum(n))

kable(t_cana)
```

## Car Access
```{r}
tabyl(vic_complete$car_access)

vic_complete <- vic_complete %>% mutate(car_access_1 = case_when(
  car_access == 1 ~ "Yes",
  car_access == 2 ~ "No"
))
tabyl(vic_complete$car_access_1)
tabyl(vic_complete$cars_household)

# Table

t_cars <- vic_complete %>%
          group_by(wave_id, vic_complete$car_access_1) %>%
            summarise(n = n()) %>%
            mutate(pct = 100*n / sum(n))

kable(t_cars)
```

## Support for AAA
### AAA Familiarity 
```{r}
tabyl(sd2$aaa_familiarity)

sd2 <- sd2 %>% mutate(aaa_familiarity_1 = case_when(
  aaa_familiarity == 1 ~ "Yes",
  aaa_familiarity == 2 ~ "No"
))

tabyl(sd2$aaa_familiarity_1)
```
## AAA Good idea
```{r}
tabyl(sd2$aaa_idea)

sd2 <- sd2 %>% mutate(aaa_idea_1 = case_when(
  aaa_idea == 1 ~ "Very good idea",
  aaa_idea == 2 ~ "Somewhat good idea",
  aaa_idea == 3 ~ "Somewhat bad idea",
  aaa_idea == 4 ~ "Very bad idea",
  aaa_idea == 77 ~ "I don't know"
))

sd2$aaa_idea_1 <- factor(sd2$aaa_idea_1, c("I don't know", "Very bad idea", "Somewhat bad idea", "Somewhat good idea", "Very good idea"))
tabyl(sd2$aaa_idea_1)


```

## AAA Idea
```{r}
AAA_idea_plot <- ggplot(data = vic_mf, aes(aaa_idea_1)) +
  geom_bar() +
  labs(title = "All Ages and Abilities Cycling Network Idea",
       x = "AAA Idea",
       y = "Number of Participants (n)") + theme(axis.text.x = element_text(angle=60, hjust=1)) + 
  facet_wrap(~ wave_id)
plot(AAA_idea_plot)
```

## AAA Cycle More
```{r}
tabyl(sd2$aaa_bike_more)

sd2 <- sd2 %>% mutate(aaa_bike_more_1 = case_when(
  aaa_bike_more == 1 ~ "Yes",
  aaa_bike_more == 2 ~ "No"
))

tabyl(sd2$aaa_bike_more_1)

# Table

t_abm <- sd2 %>%
          group_by(wave_id, sd2$aaa_bike_more_1) %>%
            summarise(n = n()) %>%
            mutate(pct = 100*n / sum(n))
kable(t_abm)
```

##Preference for Separated Bike Lane
```{r}
victoria_small_merged_1$major_street_separated_bike_lane <- factor(victoria_small_merged_1$major_street_separated_bike_lane, c( "Very uncomfortable", "Somewhat uncomfortable", "Somewhat comfortable", "Very comfortable", "I don't know/Prefer not to answer"))
tabyl(victoria_small_merged_1$major_street_separated_bike_lane)
```

## Percieved Cycling Safety in Victoria
```{r}
victoria_small_merged_1 <- victoria_small_merged_1 %>% mutate(bike_safety_1 = case_when(
  bike_safety == 1 ~ "Very safe",
  bike_safety == 2 ~ "Somewhat safe",
  bike_safety == 3 ~ "Neither safe nor unsafe",
  bike_safety == 4 ~ "Somewhat dangerous",
  bike_safety == 5 ~ "Very dangerous",
))
tabyl(victoria_small_merged_1$bike_safety_1)

victoria_small_merged_1$bike_safety_1 <- factor(victoria_small_merged_1$bike_safety_1, c( "Very safe", "Somewhat safe", "Neither safe nor unsafe", "Somewhat dangerous", "Very dangerous"))
tabyl(victoria_small_merged_1$bike_safety_1)
```

## Bike frequency by season
```{r}
summary(victoria_small_merged_1$bike_freq_a)
sd(victoria_small_merged_1$bike_freq_a)

summary(victoria_small_merged_1$bike_freq_b)
sd(victoria_small_merged_1$bike_freq_b, na.rm = TRUE)

summary(victoria_small_merged_1$bike_freq_c)
sd(victoria_small_merged_1$bike_freq_c)

summary(victoria_small_merged_1$bike_freq_d)
sd(victoria_small_merged_1$bike_freq_d, na.rm = TRUE)
```

## Cycing infrastructure preference
```{r}
tabyl(victoria_small_merged_1$path_comf)
tabyl(victoria_small_merged_1$residential_street_comf)
tabyl(victoria_small_merged_1$res_street_traffic_calming_comf)
tabyl(victoria_small_merged_1$major_street_no_bike_lane)
tabyl(victoria_small_merged_1$major_street_bike_lane)
```
